version: '3.8'

services:
  backend:
    build:
      context: ./travel-assistant-app/backend
    ports:
      - "5001:5001"
    volumes:
      - ./travel-assistant-app/backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./travel-assistant-app/frontend
    ports:
      - "8501:8501"
    volumes:
      - ./travel-assistant-app/frontend:/app
    environment:
      - BACKEND_URL=http://backend:5001
    depends_on:
      backend:
        condition: service_healthy